/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-17 01:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset='utf-8'>\r\n");
      out.write("	<meta name=\"viewport\"\r\n");
      out.write("		content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">\r\n");
      out.write("	<title>sub</title>\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/sub.css\">\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" 	");
      out.write("\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div id=\"logo\">\r\n");
      out.write("			<a href=\"index.html\"><img src=\"img/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"login\">\r\n");
      out.write("			<span><a href=\"#\">로그인</a></span>\r\n");
      out.write("			<span><a href=\"#\">회원가입</a></span>\r\n");
      out.write("			<span><a href=\"#\">고객센터</a></span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 내비게이션 영역 -->\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">BEST</a></li>\r\n");
      out.write("                <li><a href=\"#\">NEW</a></li>\r\n");
      out.write("                <li><a href=\"#\">2PACK</a></li>\r\n");
      out.write("                <li><a href=\"#\">T-shirts</a></li>\r\n");
      out.write("                <li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("                <li><a href=\"#\">Outer</a></li>\r\n");
      out.write("                <li><a href=\"#\">Zip-up</a></li>\r\n");
      out.write("                <li><a href=\"#\">Sweats</a></li>\r\n");
      out.write("                <li><a href=\"#\">Hoodie</a></li>\r\n");
      out.write("                <li><a href=\"#\">Bottom</a></li>\r\n");
      out.write("                <li><a class=\"menu\">Menu</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>로그인</h2>\r\n");
      out.write("<form action=\"login.do\" method=\"post\" name=\"frm\">\r\n");
      out.write("  <table>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>아이디</td>\r\n");
      out.write("       <td><input type=\"text\" name=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("       <td>암호</td>\r\n");
      out.write("       <td><input type=\"password\" name=\"pwd\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("       <td colspan=\"2\" align=\"center\">\r\n");
      out.write("         <input type=\"submit\" value=\"로그인\" onclick=\"return loginCheck()\">\r\n");
      out.write("         <input type=\"reset\" value=\"취소\">\r\n");
      out.write("         <input type=\"button\" value=\"회원가입\" onclick=\"location.href='join.do'\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("       <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("		<div id=\"user\">\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<h4>회원혜택</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/coupon.png\" alt=\"coupon\">\r\n");
      out.write("				<p>가입즉시<br>웰컴쿠폰 11000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/free.png\" alt=\"coupon\">\r\n");
      out.write("				<p>가입즉시<br>전제품 무료배송</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/app.png\" alt=\"coupon\">\r\n");
      out.write("				<p>회원등급별<br>최대20% 할인</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/sale.png\" alt=\"coupon\">\r\n");
      out.write("				<p>APP다운시<br>감사쿠폰 1000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/birthday.png\" alt=\"coupon\">\r\n");
      out.write("				<p>생일기념<br>축하쿠폰 1000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"but\">\r\n");
      out.write("				<a href=\"#\">회원등급 혜택</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"br\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"last\">\r\n");
      out.write("			<div id=\"one\">\r\n");
      out.write("				<span>회사소개</span>\r\n");
      out.write("				<span>이용약관</span>\r\n");
      out.write("				<span><a href=\"\"><u>개인정보처리방침</u></a></span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"two\">\r\n");
      out.write("				<p>회사주소 : 서울시 동대문구 사가정로 27길 (장안동 92-2 영신빌딩 3층) 고객센터 전화 : 1644-1429<br>\r\n");
      out.write("					사업자등록번호 : 631-87-00028 통신판매업신고 : 제2014-서울동대문-0417 상호명 : (주) 에프엠제이인터내셔날<br>\r\n");
      out.write("					대표 : 강일훈 사업자정보확인 개인정보보호책임자 : 강일훈 협찬/제휴문의 : kgnsl1@fairplay142.com</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"three\">\r\n");
      out.write("				<a href=\"https://www.fmj.co.kr/\">\r\n");
      out.write("					<p>© FMJINTERNATIONAL Corp. All rights reserved.</p>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"four\">\r\n");
      out.write("				<p>1644-1429</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"five\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">마이페이지</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">나의적립금</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">공지사항</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">문의하기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"six\">\r\n");
      out.write("				<p>MON-FRI 10:00 ~ 17:00<br>\r\n");
      out.write("					LUNCH 13:00 ~ 14:00<br>\r\n");
      out.write("					주말, 공휴일 제외</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
