/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-18 06:02:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sub1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729126772591L));
    _jspx_dependants.put("jar:file:/C:/JSP_pofol/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pofol/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset='utf-8'>\r\n");
      out.write("	<meta name=\"viewport\"\r\n");
      out.write("		content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">\r\n");
      out.write("	<title>sub</title>\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/sub.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div id=\"logo\">\r\n");
      out.write("			<a href=\"index.jsp\"><img src=\"img/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		 <div id=\"login\">\r\n");
      out.write("            <span>\r\n");
      out.write("            	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("        \r\n");
      out.write("            <span>\r\n");
      out.write(" 				");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</span>\r\n");
      out.write("            <span><a href=\"board.jsp\">게시판</a></span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 내비게이션 영역 -->\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">BEST</a></li>\r\n");
      out.write("                <li><a href=\"#\">NEW</a></li>\r\n");
      out.write("                <li><a href=\"#\">2PACK</a></li>\r\n");
      out.write("                <li><a href=\"#\">T-shirts</a></li>\r\n");
      out.write("                <li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("                <li><a href=\"#\">Outer</a></li>\r\n");
      out.write("                <li><a href=\"#\">Zip-up</a></li>\r\n");
      out.write("                <li><a href=\"#\">Sweats</a></li>\r\n");
      out.write("                <li><a href=\"#\">Hoodie</a></li>\r\n");
      out.write("                <li><a href=\"#\">Bottom</a></li>\r\n");
      out.write("                <li><a class=\"menu\">Menu</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"section\">\r\n");
      out.write("		<div id=\"one\">\r\n");
      out.write("			<a href=\"\">\r\n");
      out.write("				<span>ALL ITEM ></span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<a href=\"\">\r\n");
      out.write("				<span>BOTTOM ></span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<a href=\"\">\r\n");
      out.write("				<span><u>SHORT</u></span>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"two\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"left\">\r\n");
      out.write("				<img src=\"img/section/1.jpg\" alt=\"\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"right\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"img/logo2.PNG\" alt=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"info\">\r\n");
      out.write("					<h3>파운드마이 반팔티셔츠 올드핑크 JIST7659</h3>\r\n");
      out.write("					<div id=\"price\">\r\n");
      out.write("						<p><span>27%</span> 24,900원 <del>34,000원</del></p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"info2\">\r\n");
      out.write("					<table>\r\n");
      out.write("						<colgroup>\r\n");
      out.write("							<col width=\"170\">\r\n");
      out.write("							<col width=\"*\">\r\n");
      out.write("						</colgroup>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"tb-left\">제조사/제조국</th>\r\n");
      out.write("								<td class=\"tb-left\">대한민국/자체제작(WV)</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"tb-left\">소재</th>\r\n");
      out.write("								<td class=\"tb-left\">면(Cotton) 100%</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"tb-left\">배송정보</th>\r\n");
      out.write("								<td class=\"tb-left\">내일(화) 도착 예정<br>\r\n");
      out.write("									뚝딱배송 상품 당일 오후 12시 전 결제 시<br>오늘 수령\r\n");
      out.write("									(서울 지역)</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"tb-left\">카드 할인</th>\r\n");
      out.write("								<td class=\"tb-left\">5만원 이상 무이자 할부</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"dropdown\">\r\n");
      out.write("						<button class=\"dropbtn\">WV 회원 <span>등급별 할인액</span></button>\r\n");
      out.write("						<div class=\"dropdown-content\">\r\n");
      out.write("							<table>\r\n");
      out.write("								<colgroup>\r\n");
      out.write("									<col width=\"170\">\r\n");
      out.write("									<col width=\"*\">\r\n");
      out.write("								</colgroup>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td class=\"tb-left\" colspan=\"2\">\r\n");
      out.write("											<p>이벤트 세일 상품 및 일부 품목의 회원가는 장바구니와 구매페이지에서 최종결제금액을 확인 할 수 있습니다.\r\n");
      out.write("												*일부 이벤트 세일 상품은 해당되지 않을 수 있습니다.</p>\r\n");
      out.write("										</td>\r\n");
      out.write("\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">CR 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">35,120원 (20% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">WV 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">37,315원 (15% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">W 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">39,510원 (10% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">V 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">40,827원 (7% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">I 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">41,705원 (5% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">P 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">42,583원 (3% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">C 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">43,461원 (1% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th class=\"tb-left\">LV.00 등급</th>\r\n");
      out.write("										<td class=\"tb-left\">43,900원 (0% 할인)</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"size\">\r\n");
      out.write("					<h3>색상/사이즈</h3>\r\n");
      out.write("					<br>\r\n");
      out.write("					<div class=\"dropdown1\">\r\n");
      out.write("						<button class=\"dropbtn1\">옵션 선택</button>\r\n");
      out.write("						<div class=\"dropdown-content1\">\r\n");
      out.write("							<a href=\"#\">옵션 선택</a>\r\n");
      out.write("							<a href=\"#\">올드핑크 S</a>\r\n");
      out.write("							<a href=\"#\">올드핑크 M</a>\r\n");
      out.write("							<a href=\"#\">올드핑크 L</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"price1\">\r\n");
      out.write("					<p>총 상품 금액 <span> 0 원</span></p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"but\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<button type=\"button\">장바구니</button>\r\n");
      out.write("						<button type=\"button\" class=\"but1\">바로구매</button>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"pay\">\r\n");
      out.write("					<div class=\"pay-img\">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<img src=\"img/pay/kakao.png\" alt=\"kakao\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"pay-img\">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<img src=\"img/pay/naver.jpg\" alt=\"naver\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"move\">\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#four\">\r\n");
      out.write("					<button type=\"button\">상품상세</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#six\">\r\n");
      out.write("					<button type=\"button\">사이즈표</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#review\">\r\n");
      out.write("					<button type=\"button\">REVIEW</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#QA\">\r\n");
      out.write("					<button type=\"button\">Q&A</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"delivery\">\r\n");
      out.write("					<button type=\"button\">배송안내</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>		\r\n");
      out.write("\r\n");
      out.write("		<br><br>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"three\">\r\n");
      out.write("			<h3>&#8251;고객님의 빠른 상품수령과 원활한 배송을 위해 일부상품의 경우 분리배송 되오니 이 점 참고해주세요.</h3>\r\n");
      out.write("			<img src=\"img/sub/sub1.gif\" alt=\"sub1\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"four\">\r\n");
      out.write("			<img src=\"img/sub/sub_logo.jpg\" alt=\"\">\r\n");
      out.write("			<img src=\"img/sub/sub2.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub_text.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub3.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub4.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub5.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub6.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub7.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub8.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub9.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub10.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub11.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub12.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/sub13.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"six\">\r\n");
      out.write("			<img src=\"img/sub/size.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/size-1.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"five\">\r\n");
      out.write("			<img src=\"img/sub/last.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"seven\">\r\n");
      out.write("			<img src=\"img/sub/last_logo.jpg\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"move\">\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#four\">\r\n");
      out.write("					<button type=\"button\">상품상세</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#six\">\r\n");
      out.write("					<button type=\"button\">사이즈표</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#review\">\r\n");
      out.write("					<button type=\"button\">REVIEW</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"#QA\">\r\n");
      out.write("					<button type=\"button\">Q&A</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"move-but\">\r\n");
      out.write("				<a href=\"delivery\">\r\n");
      out.write("					<button type=\"button\">배송안내</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"review\">\r\n");
      out.write("			<img src=\"img/sub/sub_review.PNG\" alt=\"\">			\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"QA\">\r\n");
      out.write("			<img src=\"img/sub/product.PNG\" alt=\"\">			\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"delivery\">\r\n");
      out.write("			<h2>배송안내</h2><br>\r\n");
      out.write("			<p>배송기간 : 영업일 기준 <span>1~2일</span> 소요됩니다. \r\n");
      out.write("				<span class=\"small\">(사전 예약 상품 / 패키지 상품은 제외, 주소지 도착일은 \r\n");
      out.write("				평균 1~2일 정도 소요됩니다.)</span></p>\r\n");
      out.write("\r\n");
      out.write("			<p>택배사 : 우체국택배 / CJ대한통운 / 오늘의 픽업</p>\r\n");
      out.write("\r\n");
      out.write("			<p>단체복, 대량 구매를 계획 중인 고객님은 품절 없는 상품\r\n");
      out.write("				발송을 위해 Q&A 게시판에 재고 문의를 해주세요.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("<!--섹션 마지막 div-->\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<div id=\"user\">\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<h4>회원혜택</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/coupon.png\" alt=\"coupon\">\r\n");
      out.write("				<p>가입즉시<br>웰컴쿠폰 11000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/free.png\" alt=\"coupon\">\r\n");
      out.write("				<p>가입즉시<br>전제품 무료배송</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/app.png\" alt=\"coupon\">\r\n");
      out.write("				<p>회원등급별<br>최대20% 할인</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/sale.png\" alt=\"coupon\">\r\n");
      out.write("				<p>APP다운시<br>감사쿠폰 1000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon\">\r\n");
      out.write("				<img src=\"img/footer/birthday.png\" alt=\"coupon\">\r\n");
      out.write("				<p>생일기념<br>축하쿠폰 1000원</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"but\">\r\n");
      out.write("				<a href=\"#\">회원등급 혜택</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"br\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"last\">\r\n");
      out.write("			<div id=\"one\">\r\n");
      out.write("				<span>회사소개</span>\r\n");
      out.write("				<span>이용약관</span>\r\n");
      out.write("				<span><a href=\"\"><u>개인정보처리방침</u></a></span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"two\">\r\n");
      out.write("				<p>회사주소 : 서울시 동대문구 사가정로 27길 (장안동 92-2 영신빌딩 3층) 고객센터 전화 : 1644-1429<br>\r\n");
      out.write("					사업자등록번호 : 631-87-00028 통신판매업신고 : 제2014-서울동대문-0417 상호명 : (주) 에프엠제이인터내셔날<br>\r\n");
      out.write("					대표 : 강일훈 사업자정보확인 개인정보보호책임자 : 강일훈 협찬/제휴문의 : kgnsl1@fairplay142.com</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"three\">\r\n");
      out.write("				<a href=\"https://www.fmj.co.kr/\">\r\n");
      out.write("					<p>© FMJINTERNATIONAL Corp. All rights reserved.</p>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"four\">\r\n");
      out.write("				<p>1644-1429</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"five\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">마이페이지</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">나의적립금</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">공지사항</a></li>\r\n");
      out.write("					<br>\r\n");
      out.write("					<li><a href=\"\">문의하기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"six\">\r\n");
      out.write("				<p>MON-FRI 10:00 ~ 17:00<br>\r\n");
      out.write("					LUNCH 13:00 ~ 14:00<br>\r\n");
      out.write("					주말, 공휴일 제외</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            		");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            	\r\n");
          out.write("            		");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /sub1.jsp(29,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser.username}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            			<a href=\"login.do\">로그인</a>\r\n");
          out.write("            		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<a href=\"update.do\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("            		");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        			");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        \r\n");
          out.write("        			");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    			");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /sub1.jsp(41,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginUser.username}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            			<a href=\"logout.do\">로그아웃</a>\r\n");
          out.write("        			");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            			<a href=\"join.do\">회원가입</a>\r\n");
          out.write("        			");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
